services:
  php:
    build: ./Docker/php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:delegated
      - ./Docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf:delegated
    environment:
      docker: 'true'
      PHP_IDE_CONFIG: serverName=docker
